name: Validate JSON

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: .zenodo.json
          schema: test/json/legacyrecord.json
          fail-on-missing-schema: true
          strict: false
